"""initial schema

Revision ID: 1d0aceb3ba0f
Revises: 
Create Date: 2026-08-17 05:53:48.866161
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001_initial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('level_interest', sa.Enum('LEVEL_1', 'LEVEL_2', 'LEVEL_3', name='training_level'), nullable=True),
    sa.Column('primary_goal', sa.String(length=120), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'CONVERTED', 'CLOSED', name='lead_status'), nullable=False),
    sa.Column('consent_marketing', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads'))
    )
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('programs',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('level', sa.Enum('LEVEL_1', 'LEVEL_2', 'LEVEL_3', name='training_level'), nullable=False),
    sa.Column('tagline', sa.String(length=200), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('session_minutes', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('billing_period', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('features', postgresql.ARRAY(sa.String(length=200)), nullable=False),
    sa.Column('best_for', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_accepting_clients', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programs'))
    )
    op.create_index(op.f('ix_programs_slug'), 'programs', ['slug'], unique=True)
    op.create_table('testimonials',
    sa.Column('client_name', sa.String(length=80), nullable=False),
    sa.Column('level_label', sa.String(length=60), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('result_metric', sa.String(length=80), nullable=True),
    sa.Column('weeks_in', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_testimonials'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.Enum('CLIENT', 'COACH', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('body_measurements',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('chest_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('waist_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('hips_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('left_arm_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('right_arm_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('left_thigh_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('right_thigh_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('neck_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('body_fat_pct', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name=op.f('fk_body_measurements_client_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_body_measurements')),
    sa.UniqueConstraint('client_id', 'log_date', name=op.f('uq_body_measurements_client_id'))
    )
    op.create_index(op.f('ix_body_measurements_client_id'), 'body_measurements', ['client_id'], unique=False)
    op.create_index(op.f('ix_body_measurements_log_date'), 'body_measurements', ['log_date'], unique=False)
    op.create_table('cardio_logs',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('activity_type', sa.Enum('WALKING', 'RUNNING', 'CYCLING', 'ROWING', 'ELLIPTICAL', 'STAIR_CLIMBER', 'SWIMMING', 'HIIT', 'SPORTS', 'OTHER', name='cardio_type'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('avg_heart_rate', sa.Integer(), nullable=True),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.Column('intensity', sa.Enum('LOW', 'MODERATE', 'HIGH', name='intensity'), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'WATCH', name='data_source'), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name=op.f('fk_cardio_logs_client_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cardio_logs'))
    )
    op.create_index(op.f('ix_cardio_logs_client_id'), 'cardio_logs', ['client_id'], unique=False)
    op.create_index(op.f('ix_cardio_logs_log_date'), 'cardio_logs', ['log_date'], unique=False)
    op.create_table('client_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.Enum('FEMALE', 'MALE', name='sex'), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('starting_weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('current_weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('goal_weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('goal', sa.Enum('CUT', 'MAINTAIN', 'BUILD', name='goal'), nullable=False),
    sa.Column('activity_level', sa.Enum('SEDENTARY', 'LIGHT', 'MODERATE', 'ACTIVE', 'VERY_ACTIVE', name='activity_level'), nullable=False),
    sa.Column('unit_system', sa.Enum('METRIC', 'IMPERIAL', name='unit_system'), nullable=False),
    sa.Column('level', sa.Enum('LEVEL_1', 'LEVEL_2', 'LEVEL_3', name='training_level'), nullable=False),
    sa.Column('phase', sa.String(length=60), nullable=True),
    sa.Column('program_start_date', sa.Date(), nullable=True),
    sa.Column('program_week', sa.Integer(), nullable=False),
    sa.Column('program_total_weeks', sa.Integer(), nullable=False),
    sa.Column('calorie_target', sa.Integer(), nullable=True),
    sa.Column('protein_target_g', sa.Integer(), nullable=True),
    sa.Column('carb_target_g', sa.Integer(), nullable=True),
    sa.Column('fat_target_g', sa.Integer(), nullable=True),
    sa.Column('weekly_workout_target', sa.Integer(), nullable=False),
    sa.Column('sleep_target_hours', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('weekly_cardio_target_min', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('coach_notes', sa.Text(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_client_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_client_profiles_user_id'))
    )
    op.create_table('consultation_bookings',
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('preferred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='booking_status'), nullable=False),
    sa.Column('coach_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name=op.f('fk_consultation_bookings_client_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultation_bookings'))
    )
    op.create_index(op.f('ix_consultation_bookings_client_id'), 'consultation_bookings', ['client_id'], unique=False)
    op.create_index(op.f('ix_consultation_bookings_email'), 'consultation_bookings', ['email'], unique=False)
    op.create_table('exercises',
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('target_muscle', sa.String(length=80), nullable=False),
    sa.Column('secondary_muscles', postgresql.ARRAY(sa.String(length=80)), nullable=False),
    sa.Column('equipment', sa.Enum('BARBELL', 'DUMBBELL', 'MACHINE', 'CABLE', 'BODYWEIGHT', 'KETTLEBELL', 'BAND', 'OTHER', name='equipment'), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('coaching_cue', sa.String(length=300), nullable=True),
    sa.Column('min_level', sa.Enum('LEVEL_1', 'LEVEL_2', 'LEVEL_3', name='training_level'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_exercises_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises'))
    )
    op.create_index(op.f('ix_exercises_equipment'), 'exercises', ['equipment'], unique=False)
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=False)
    op.create_index(op.f('ix_exercises_slug'), 'exercises', ['slug'], unique=True)
    op.create_index(op.f('ix_exercises_target_muscle'), 'exercises', ['target_muscle'], unique=False)
    op.create_table('meal_plans',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('phase', sa.Enum('CUT', 'MAINTAIN', 'BUILD', name='goal'), nullable=False),
    sa.Column('calorie_target', sa.Integer(), nullable=False),
    sa.Column('protein_target_g', sa.Integer(), nullable=False),
    sa.Column('carb_target_g', sa.Integer(), nullable=False),
    sa.Column('fat_target_g', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_meal_plans_assigned_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name=op.f('fk_meal_plans_client_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_plans'))
    )
    op.create_index(op.f('ix_meal_plans_client_id'), 'meal_plans', ['client_id'], unique=False)
    op.create_index(op.f('ix_meal_plans_is_active'), 'meal_plans', ['is_active'], unique=False)
    op.create_table('message_threads',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name=op.f('fk_message_threads_client_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], name=op.f('fk_message_threads_coach_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_threads'))
    )
    op.create_index(op.f('ix_message_threads_client_id'), 'message_threads', ['client_id'], unique=False)
    op.create_index(op.f('ix_message_threads_coach_id'), 'message_threads', ['coach_id'], unique=False)
    op.create_index(op.f('ix_message_threads_last_message_at'), 'message_threads', ['last_message_at'], unique=False)
    op.create_table('progress_photos',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('pose', sa.Enum('FRONT', 'SIDE', 'BACK', name='photo_pose'), nullable=False),
    sa.Column('file_key', sa.String(length=400), nullable=False),
    sa.Column('content_type', sa.String(length=60), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('shared_with_coach', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name=op.f('fk_progress_photos_client_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_progress_photos'))
    )
    op.create_index(op.f('ix_progress_photos_client_id'), 'progress_photos', ['client_id'], unique=False)
    op.create_index(op.f('ix_progress_photos_log_date'), 'progress_photos', ['log_date'], unique=False)
    op.create_table('refresh_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_sessions'))
    )
    op.create_index(op.f('ix_refresh_sessions_token_hash'), 'refresh_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_sessions_user_id'), 'refresh_sessions', ['user_id'], unique=False)
    op.create_table('sleep_logs',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('bedtime', sa.Time(), nullable=True),
    sa.Column('wake_time', sa.Time(), nullable=True),
    sa.Column('hours_slept', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('awakenings', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name=op.f('fk_sleep_logs_client_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sleep_logs')),
    sa.UniqueConstraint('client_id', 'log_date', name=op.f('uq_sleep_logs_client_id'))
    )
    op.create_index(op.f('ix_sleep_logs_client_id'), 'sleep_logs', ['client_id'], unique=False)
    op.create_index(op.f('ix_sleep_logs_log_date'), 'sleep_logs', ['log_date'], unique=False)
    op.create_table('weight_logs',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name=op.f('fk_weight_logs_client_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weight_logs')),
    sa.UniqueConstraint('client_id', 'log_date', name=op.f('uq_weight_logs_client_id'))
    )
    op.create_index(op.f('ix_weight_logs_client_id'), 'weight_logs', ['client_id'], unique=False)
    op.create_index(op.f('ix_weight_logs_log_date'), 'weight_logs', ['log_date'], unique=False)
    op.create_table('workout_plans',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=True),
    sa.Column('assigned_by_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('level', sa.Enum('LEVEL_1', 'LEVEL_2', 'LEVEL_3', name='training_level'), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('total_weeks', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_workout_plans_assigned_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name=op.f('fk_workout_plans_client_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_workout_plans_program_id_programs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_plans'))
    )
    op.create_index(op.f('ix_workout_plans_client_id'), 'workout_plans', ['client_id'], unique=False)
    op.create_index(op.f('ix_workout_plans_is_active'), 'workout_plans', ['is_active'], unique=False)
    op.create_table('meals',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('serve_time', sa.Time(), nullable=True),
    sa.Column('icon', sa.String(length=16), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Integer(), nullable=False),
    sa.Column('carbs_g', sa.Integer(), nullable=False),
    sa.Column('fat_g', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['meal_plans.id'], name=op.f('fk_meals_plan_id_meal_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meals'))
    )
    op.create_index(op.f('ix_meals_plan_id'), 'meals', ['plan_id'], unique=False)
    op.create_table('messages',
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['message_threads.id'], name=op.f('fk_messages_thread_id_message_threads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    op.create_table('workout_days',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('focus', sa.String(length=80), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['workout_plans.id'], name=op.f('fk_workout_days_plan_id_workout_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_days'))
    )
    op.create_index(op.f('ix_workout_days_plan_id'), 'workout_days', ['plan_id'], unique=False)
    op.create_table('meal_items',
    sa.Column('meal_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('fk_meal_items_meal_id_meals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_items'))
    )
    op.create_index(op.f('ix_meal_items_meal_id'), 'meal_items', ['meal_id'], unique=False)
    op.create_table('meal_logs',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('meal_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('actual_calories', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name=op.f('fk_meal_logs_client_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('fk_meal_logs_meal_id_meals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_logs')),
    sa.UniqueConstraint('client_id', 'meal_id', 'log_date', name=op.f('uq_meal_logs_client_id'))
    )
    op.create_index(op.f('ix_meal_logs_client_id'), 'meal_logs', ['client_id'], unique=False)
    op.create_index(op.f('ix_meal_logs_log_date'), 'meal_logs', ['log_date'], unique=False)
    op.create_table('workout_day_exercises',
    sa.Column('day_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('rep_range', sa.String(length=30), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('tempo', sa.String(length=20), nullable=True),
    sa.Column('target_weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('coach_note', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['workout_days.id'], name=op.f('fk_workout_day_exercises_day_id_workout_days'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_workout_day_exercises_exercise_id_exercises'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_day_exercises'))
    )
    op.create_index(op.f('ix_workout_day_exercises_day_id'), 'workout_day_exercises', ['day_id'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('day_id', sa.UUID(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', name='session_status'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.Column('client_notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name=op.f('fk_workout_sessions_client_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['day_id'], ['workout_days.id'], name=op.f('fk_workout_sessions_day_id_workout_days'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_sessions')),
    sa.UniqueConstraint('client_id', 'day_id', 'session_date', name=op.f('uq_workout_sessions_client_id'))
    )
    op.create_index(op.f('ix_workout_sessions_client_id'), 'workout_sessions', ['client_id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_session_date'), 'workout_sessions', ['session_date'], unique=False)
    op.create_table('set_logs',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('day_exercise_id', sa.UUID(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('rpe', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['day_exercise_id'], ['workout_day_exercises.id'], name=op.f('fk_set_logs_day_exercise_id_workout_day_exercises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], name=op.f('fk_set_logs_session_id_workout_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_set_logs'))
    )
    op.create_index(op.f('ix_set_logs_session_id'), 'set_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_set_logs_session_id'), table_name='set_logs')
    op.drop_table('set_logs')
    op.drop_index(op.f('ix_workout_sessions_session_date'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_client_id'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_workout_day_exercises_day_id'), table_name='workout_day_exercises')
    op.drop_table('workout_day_exercises')
    op.drop_index(op.f('ix_meal_logs_log_date'), table_name='meal_logs')
    op.drop_index(op.f('ix_meal_logs_client_id'), table_name='meal_logs')
    op.drop_table('meal_logs')
    op.drop_index(op.f('ix_meal_items_meal_id'), table_name='meal_items')
    op.drop_table('meal_items')
    op.drop_index(op.f('ix_workout_days_plan_id'), table_name='workout_days')
    op.drop_table('workout_days')
    op.drop_index(op.f('ix_messages_thread_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_meals_plan_id'), table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_workout_plans_is_active'), table_name='workout_plans')
    op.drop_index(op.f('ix_workout_plans_client_id'), table_name='workout_plans')
    op.drop_table('workout_plans')
    op.drop_index(op.f('ix_weight_logs_log_date'), table_name='weight_logs')
    op.drop_index(op.f('ix_weight_logs_client_id'), table_name='weight_logs')
    op.drop_table('weight_logs')
    op.drop_index(op.f('ix_sleep_logs_log_date'), table_name='sleep_logs')
    op.drop_index(op.f('ix_sleep_logs_client_id'), table_name='sleep_logs')
    op.drop_table('sleep_logs')
    op.drop_index(op.f('ix_refresh_sessions_user_id'), table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_token_hash'), table_name='refresh_sessions')
    op.drop_table('refresh_sessions')
    op.drop_index(op.f('ix_progress_photos_log_date'), table_name='progress_photos')
    op.drop_index(op.f('ix_progress_photos_client_id'), table_name='progress_photos')
    op.drop_table('progress_photos')
    op.drop_index(op.f('ix_message_threads_last_message_at'), table_name='message_threads')
    op.drop_index(op.f('ix_message_threads_coach_id'), table_name='message_threads')
    op.drop_index(op.f('ix_message_threads_client_id'), table_name='message_threads')
    op.drop_table('message_threads')
    op.drop_index(op.f('ix_meal_plans_is_active'), table_name='meal_plans')
    op.drop_index(op.f('ix_meal_plans_client_id'), table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_index(op.f('ix_exercises_target_muscle'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_slug'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_equipment'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_consultation_bookings_email'), table_name='consultation_bookings')
    op.drop_index(op.f('ix_consultation_bookings_client_id'), table_name='consultation_bookings')
    op.drop_table('consultation_bookings')
    op.drop_table('client_profiles')
    op.drop_index(op.f('ix_cardio_logs_log_date'), table_name='cardio_logs')
    op.drop_index(op.f('ix_cardio_logs_client_id'), table_name='cardio_logs')
    op.drop_table('cardio_logs')
    op.drop_index(op.f('ix_body_measurements_log_date'), table_name='body_measurements')
    op.drop_index(op.f('ix_body_measurements_client_id'), table_name='body_measurements')
    op.drop_table('body_measurements')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('testimonials')
    op.drop_index(op.f('ix_programs_slug'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
