"""Import every model here so Alembic autogenerate and SQLAlchemy see them all."""

from app.core.database import Base
from app.models.billing import Payment, Subscription, WebhookEvent
from app.models.catalog import Exercise, Program, Testimonial
from app.models.engagement import (
    ConsultationBooking,
    Lead,
    Message,
    MessageAttachment,
    MessageThread,
)
from app.models.enums import (
    ActivityLevel,
    AttachmentKind,
    BookingStatus,
    CardioType,
    DataSource,
    Equipment,
    ForceType,
    GalleryCategory,
    Goal,
    Intensity,
    LeadStatus,
    Mechanics,
    MuscleGroup,
    PhotoPose,
    SessionStatus,
    Sex,
    SubscriptionStatus,
    TrainingLevel,
    TutorialCategory,
    UnitSystem,
    UserRole,
    VideoProvider,
)
from app.models.gallery import GalleryImage
from app.models.media import VideoTutorial
from app.models.nutrition import Meal, MealItem, MealLog, MealPlan
from app.models.tracking import (
    BodyMeasurement,
    CardioLog,
    ProgressPhoto,
    SleepLog,
    WeightLog,
)
from app.models.training import SetLog, WorkoutDay, WorkoutDayExercise, WorkoutPlan, WorkoutSession
from app.models.user import ClientProfile, RefreshSession, User

__all__ = [
    "ActivityLevel",
    "AttachmentKind",
    "Base",
    "BodyMeasurement",
    "BookingStatus",
    "CardioLog",
    "CardioType",
    "ClientProfile",
    "ConsultationBooking",
    "DataSource",
    "Equipment",
    "Exercise",
    "ForceType",
    "GalleryCategory",
    "GalleryImage",
    "Goal",
    "Intensity",
    "Lead",
    "LeadStatus",
    "Meal",
    "MealItem",
    "MealLog",
    "MealPlan",
    "Mechanics",
    "Message",
    "MessageAttachment",
    "MessageThread",
    "MuscleGroup",
    "PhotoPose",
    "Program",
    "ProgressPhoto",
    "RefreshSession",
    "SessionStatus",
    "SetLog",
    "Sex",
    "SleepLog",
    "Testimonial",
    "Payment",
    "Subscription",
    "SubscriptionStatus",
    "TrainingLevel",
    "WebhookEvent",
    "TutorialCategory",
    "UnitSystem",
    "User",
    "UserRole",
    "VideoProvider",
    "VideoTutorial",
    "WeightLog",
    "WorkoutDay",
    "WorkoutDayExercise",
    "WorkoutPlan",
    "WorkoutSession",
]